### ISSUE TITLE
Dependency!

### ISSUE THREAD

**Issue by SalomonSmeke** [Rhernandez513/Comp-330-work#2]
Yeah. like aid mentioned. It just seems like not much had to be done. I get using an existing project, but throw it into a node.js thing and make something out of it. not just expose it.

Also no tests, which are crucial to the "spirit" of the assignment.

**Comment by Rhernandez513** [comment]
[Unit tests built into original project](https://github.com/edburnett/twitter-text-python/blob/master/ttp/tests.py)

[Added some unit tests addressing possible cases mentioned in specification](https://github.com/Rhernandez513/Comp-330-work/commit/bccd3d512f25ffd99e353aa15c38977bba2900d1)

No hard feelings, but protip, add your comment to the issue Aid opened originally instead of opening a second issue.

**Comment by SalomonSmeke** [comment]
In a class assignment where participation is based on opening issues, its acceptable.

Double pro tip. do your homework instead of using an existing project.
